services:
  zipkin-server:
    image: openzipkin/zipkin:2.23
    container_name: zipkin-server
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - tracing

networks:
  tracing:
    driver: bridge
